import { useRef, useState } from "react";
import { Calculator, BadgeIndianRupee, FileUp, Check, Download, Scale } from "lucide-react";
import { BrandMark } from "../../components/Logo";
import { useApp } from "../../app/AppContext";
import { featureByKey } from "../../lib/features";
import { callFeature, fileToInlineData } from "../../lib/api";
import { FeatureShell } from "../../components/FeatureShell";
import { Thinking, ListBlock, ResultCard, MockNote } from "../../components/ui";
import { computeTax, compareRegimes, inr, TaxResult, Comparison } from "./taxEngine";

const ACCENT = "#A06A1F";

interface Advice {
  summary: string;
  answer?: string;
  tips?: string[];
  regimeHint?: string;
  disclaimer?: string;
  _mock?: boolean;
}

export function Kar({ onBack, embedded }: { onBack?: () => void; embedded?: boolean }) {
  const meta = featureByKey("kar");
  const { t, lang } = useApp();
  const [f, setF] = useState({ salary: "", tds: "", other: "", stcg: "", ltcg: "", deductions: "" });
  const [res, setRes] = useState<TaxResult | null>(null);
  const [cmp, setCmp] = useState<Comparison | null>(null);
  const [q, setQ] = useState("");
  const [advice, setAdvice] = useState<Advice | null>(null);
  const [loading, setLoading] = useState(false);
  const [parsing, setParsing] = useState(false);
  const [parsed, setParsed] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);

  async function onForm16(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    setParsing(true);
    setParsed(false);
    try {
      const inline = await fileToInlineData(file);
      const d = await callFeature<{ grossSalary?: number; tds?: number; otherIncome?: number }>("form16", { file: inline, language: lang.name });
      setF((p) => ({
        ...p,
        salary: d.grossSalary != null ? String(d.grossSalary) : p.salary,
        tds: d.tds != null ? String(d.tds) : p.tds,
        other: d.otherIncome ? String(d.otherIncome) : p.other,
      }));
      setParsed(true);
    } catch {
      /* ignore */
    } finally {
      setParsing(false);
      if (fileRef.current) fileRef.current.value = "";
    }
  }

  const num = (s: string) => {
    const n = parseFloat(String(s).replace(/[^0-9.]/g, ""));
    return isNaN(n) ? 0 : n;
  };
  const set = (k: string, v: string) => setF((p) => ({ ...p, [k]: v }));

  function calc() {
    const input = { salary: num(f.salary), tds: num(f.tds), otherIncome: num(f.other), equitySTCG: num(f.stcg), equityLTCG: num(f.ltcg) };
    setRes(computeTax(input));
    setCmp(compareRegimes(input, num(f.deductions)));
    setAdvice(null);
  }

  function exportPdf() {
    if (!res) return;
    const row = (l: string, v: string, b = false) => `<tr><td>${l}</td><td style="text-align:right${b ? ";font-weight:700" : ""}">${v}</td></tr>`;
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>Saarthi Tax Summary · AY 2026-27</title>
<style>
  body{font-family:'Hanken Grotesk',Arial,sans-serif;color:#1a1714;max-width:680px;margin:32px auto;padding:0 24px}
  h1{font-size:22px;margin:0} .sub{color:#6e675c;font-size:13px;margin:4px 0 20px}
  .hero{display:flex;justify-content:space-between;align-items:center;background:${res.isRefund ? "#E4F1EA" : "#F5ECD9"};padding:16px 20px;border-radius:14px;margin-bottom:20px}
  .hero b{font-size:24px;color:${res.isRefund ? "#2E6F52" : "#7C5115"}}
  table{width:100%;border-collapse:collapse;font-size:14px} td{padding:7px 0;border-bottom:1px solid #eee}
  .foot{margin-top:24px;color:#9a968e;font-size:11px}
</style></head><body>
  <h1>Saarthi · Income Tax Summary</h1>
  <div class="sub">New regime · AY 2026-27 (FY 2025-26) · generated by Lekh</div>
  <div class="hero"><span>${res.isRefund ? t("tx.refund") : t("tx.payable")}</span><b>${inr(res.netPayable)}</b></div>
  <table>
    ${row(t("tx.salary"), inr(num(f.salary)))}
    ${row(t("tx.stdded"), "− " + inr(res.standardDeduction))}
    ${row(t("tx.taxable"), inr(res.normalIncome), true)}
    ${row(t("tx.slabtax"), inr(res.slabTax))}
    ${res.rebate87A ? row(t("tx.rebate"), "− " + inr(res.rebate87A)) : ""}
    ${res.marginalRelief ? row(t("tx.relief"), "− " + inr(res.marginalRelief)) : ""}
    ${res.capitalGainsTax ? row(t("tx.cgtax"), inr(res.capitalGainsTax)) : ""}
    ${row(t("tx.cess"), inr(res.cess))}
    ${row(t("tx.total"), inr(res.totalLiability), true)}
    ${row(t("tx.tdsPaid"), "− " + inr(res.tds))}
    ${row(res.isRefund ? t("tx.refund") : t("tx.payable"), inr(res.netPayable), true)}
    ${cmp ? row(t("tx.oldRegime") + " (total)", inr(cmp.oldTotal)) : ""}
  </table>
  <div class="foot">Computed deterministically by Saarthi. General guidance, not a substitute for a chartered accountant.</div>
  <script>setTimeout(function(){window.print()},250)</script>
</body></html>`;
    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(html);
    w.document.close();
  }

  async function getAdvice() {
    if (!res) return;
    setLoading(true);
    const figures = [
      `Gross salary ${inr(num(f.salary))}`,
      `Standard deduction ${inr(res.standardDeduction)}`,
      `Taxable (slab) income ${inr(res.normalIncome)}`,
      `Slab tax ${inr(res.slabTax)}`,
      res.rebate87A ? `87A rebate ${inr(res.rebate87A)}` : "",
      res.marginalRelief ? `Marginal relief ${inr(res.marginalRelief)}` : "",
      res.capitalGainsTax ? `Capital gains tax ${inr(res.capitalGainsTax)}` : "",
      `Cess ${inr(res.cess)}`,
      `Total liability ${inr(res.totalLiability)}`,
      `TDS paid ${inr(res.tds)}`,
      `${res.isRefund ? "Refund" : "Net payable"} ${inr(res.netPayable)}`,
    ].filter(Boolean).join("; ");
    try {
      setAdvice(await callFeature<Advice>("kar", { figures, question: q, language: lang.name }));
    } catch {
      /* mock fallback */
    } finally {
      setLoading(false);
    }
  }

  const Field = ({ k, label }: { k: keyof typeof f; label: string }) => (
    <label className="block">
      <span className="mb-1.5 block text-sm font-medium text-graphite deva">{label}</span>
      <div className="relative">
        <BadgeIndianRupee className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-faint" />
        <input value={f[k]} onChange={(e) => set(k, e.target.value)} inputMode="numeric" className="field pl-9" />
      </div>
    </label>
  );

  const Row = ({ label, value, sub, strong, color }: { label: string; value: string; sub?: boolean; strong?: boolean; color?: string }) => (
    <div className={`flex items-center justify-between ${sub ? "text-sm text-muted" : "text-[15px] text-graphite"} ${strong ? "font-semibold text-ink" : ""}`}>
      <span className="deva">{label}</span>
      <span style={color ? { color } : undefined}>{value}</span>
    </div>
  );

  return (
    <FeatureShell meta={meta} onBack={onBack} embedded={embedded}>
      <div className="card p-6 sm:p-7">
        <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
          <span className="pill" style={{ color: ACCENT }}><Calculator className="h-3.5 w-3.5" /> {t("tx.regime")}</span>
          <input ref={fileRef} type="file" accept="application/pdf,image/*" onChange={onForm16} className="hidden" />
          <button onClick={() => fileRef.current?.click()} disabled={parsing} className="btn-ghost text-sm">
            <FileUp className="h-4 w-4" /> {t("tx.upload")}
          </button>
        </div>

        {parsing && <div className="mb-4"><Thinking label={t("tx.parsing")} /></div>}
        {parsed && !parsing && (
          <div className="mb-4 flex items-center gap-2 rounded-xl border border-verdant/30 bg-verdant/[0.06] px-3 py-2 text-sm text-verdant deva">
            <Check className="h-4 w-4" /> {t("tx.parsed")}
          </div>
        )}

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <Field k="salary" label={t("tx.salary")} />
          <Field k="tds" label={t("tx.tds")} />
          <Field k="other" label={t("tx.other")} />
          <Field k="stcg" label={t("tx.stcg")} />
          <Field k="ltcg" label={t("tx.ltcg")} />
          <Field k="deductions" label={t("tx.deductions")} />
        </div>
        <button onClick={calc} className="btn-accent mt-5 text-[15px]" style={{ background: ACCENT }}>
          <Calculator className="h-4 w-4" /> {t("tx.calc")}
        </button>
      </div>

      {res && (
        <div className="mt-6 space-y-5">
          <ResultCard accent={meta.accent}>
            {/* headline refund / payable */}
            <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl p-5" style={{ background: res.isRefund ? "#E4F1EA" : meta.tint }}>
              <span className="display text-lg font-bold" style={{ color: res.isRefund ? "#2E6F52" : meta.accentDark }}>
                {res.isRefund ? t("tx.refund") : t("tx.payable")}
              </span>
              <span className="display text-3xl font-bold" style={{ color: res.isRefund ? "#2E6F52" : meta.accentDark }}>{inr(res.netPayable)}</span>
            </div>

            {/* breakdown */}
            <div className="mt-5 space-y-2.5">
              <Row label={t("tx.salary")} value={inr(num(f.salary))} />
              <Row label={`${t("tx.stdded")}`} value={`− ${inr(res.standardDeduction)}`} sub />
              <Row label={t("tx.taxable")} value={inr(res.normalIncome)} strong />
            </div>

            {res.slabs.length > 0 && (
              <div className="mt-5">
                <h4 className="mb-2 text-sm font-semibold uppercase tracking-wide text-muted deva">{t("tx.slabbreak")}</h4>
                <div className="overflow-hidden rounded-2xl border border-line">
                  {res.slabs.map((s, i) => (
                    <div key={i} className="flex items-center justify-between border-b border-line px-4 py-2.5 text-sm last:border-0">
                      <span className="text-graphite">{s.range} · {s.rate}%</span>
                      <span className="text-muted">{inr(s.taxable)} → <span className="font-medium text-ink">{inr(s.tax)}</span></span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="mt-5 space-y-2.5 border-t border-line pt-4">
              <Row label={t("tx.slabtax")} value={inr(res.slabTax)} />
              {res.rebate87A > 0 && <Row label={t("tx.rebate")} value={`− ${inr(res.rebate87A)}`} sub color="#2E6F52" />}
              {res.marginalRelief > 0 && <Row label={t("tx.relief")} value={`− ${inr(res.marginalRelief)}`} sub color="#2E6F52" />}
              {res.capitalGainsTax > 0 && <Row label={t("tx.cgtax")} value={inr(res.capitalGainsTax)} />}
              <Row label={t("tx.cess")} value={inr(res.cess)} sub />
              <Row label={t("tx.total")} value={inr(res.totalLiability)} strong />
              <Row label={t("tx.tdsPaid")} value={`− ${inr(res.tds)}`} sub />
            </div>
          </ResultCard>

          {/* regime comparison + export */}
          {cmp && (
            <div className="card p-6">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <h3 className="display flex items-center gap-2 text-lg font-bold deva"><Scale className="h-5 w-5" style={{ color: ACCENT }} /> {t("tx.compare")}</h3>
                <button onClick={exportPdf} className="btn-ghost text-sm"><Download className="h-4 w-4" /> {t("tx.export")}</button>
              </div>
              <div className="mt-4 grid gap-3 sm:grid-cols-2">
                {[
                  { key: "new", label: t("tx.newRegime"), total: cmp.newTotal },
                  { key: "old", label: t("tx.oldRegime"), total: cmp.oldTotal },
                ].map((r) => {
                  const best = cmp.better === r.key || cmp.better === "same";
                  return (
                    <div key={r.key} className="rounded-2xl border-2 p-5 transition-colors" style={{ borderColor: best ? "#2E6F52" : "#E7E6E3", background: best ? "#E4F1EA" : "#fff" }}>
                      <div className="flex items-center justify-between">
                        <span className="text-sm font-medium text-graphite deva">{r.label}</span>
                        {best && <span className="flex items-center gap-1 text-xs font-semibold text-verdant"><Check className="h-3.5 w-3.5" /> best</span>}
                      </div>
                      <div className="display mt-1 text-2xl font-bold" style={{ color: best ? "#2E6F52" : "#34322C" }}>{inr(r.total)}</div>
                    </div>
                  );
                })}
              </div>
              <div className="mt-4 flex items-center justify-between rounded-2xl bg-ink px-5 py-3.5 text-white">
                <span className="text-sm font-medium deva">{cmp.better === "same" ? t("tx.same") : cmp.better === "new" ? t("tx.betterNew") : t("tx.betterOld")}</span>
                {cmp.saving > 0 && <span className="display font-bold">{t("tx.savingLabel")} {inr(cmp.saving)}</span>}
              </div>
              <p className="mt-3 text-xs text-faint deva">{t("tx.compareNote")}</p>
            </div>
          )}

          {/* AI advisor */}
          <div className="card p-6">
            <h3 className="display text-lg font-bold deva">{t("tx.advisor")}</h3>
            <textarea value={q} onChange={(e) => setQ(e.target.value)} rows={2} placeholder={t("tx.advisorPh")} className="field mt-3 resize-none deva" />
            <button onClick={getAdvice} disabled={loading} className="btn-primary mt-3 text-[15px]"><BrandMark className="h-4 w-4" /> {t("tx.getTips")}</button>

            {loading && <div className="mt-5"><Thinking label={t("common.running")} /></div>}

            {advice && !loading && (
              <div className="mt-5 rounded-2xl border p-5 deva" style={{ borderColor: meta.accent, background: meta.tint }}>
                <p className="text-[15px] font-medium text-ink">{advice.summary}</p>
                {advice.answer && <p className="mt-2 text-sm text-graphite">{advice.answer}</p>}
                {advice.tips?.length ? <div className="mt-4"><ListBlock title={t("common.result")} items={advice.tips} tone="good" /></div> : null}
                {advice.regimeHint && (
                  <div className="mt-4 rounded-xl bg-paper p-3 text-sm">
                    <span className="font-semibold text-graphite">{t("tx.regimeHint")}: </span>
                    <span className="text-muted">{advice.regimeHint}</span>
                  </div>
                )}
                {advice.disclaimer && <p className="mt-3 text-xs text-faint">{advice.disclaimer}</p>}
                {advice._mock && <MockNote text={t("common.sample")} />}
              </div>
            )}
          </div>
        </div>
      )}
    </FeatureShell>
  );
}
